parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     feedtags
    database_user:     root
    database_password: ~
    #database_path:     ~

    mailer_transport: smtp
    mailer_host:      127.0.0.1
    mailer_user:      ~
    mailer_password:  ~

    locale: en
    secret: 788c37925b40e987454a153bdf7af054314d0d09
