hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

google_login:
    pattern: /login/check-google

# FeedtagsApplicationBundle Routes
feedtags_application:
    resource: "@FeedtagsApplicationBundle/Resources/config/routing.yml"
    prefix:   /

