<?php

namespace Feedtags\ApplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Feedtags\ApplicationBundle\Entity\Feed;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    /**
     * Persist a Feed entity to database
     *
     * @param Feed $feed
     *
     * @return int Id of the saved Feed
     */
    public function save(Feed $feed)
    {
        $entityManager = $this->getEntityManager();

        $entityManager->persist($feed);
        $entityManager->flush($feed);

        return $feed->getId();
    }

    /**
     * Remove a Feed entity from database
     *
     * @param Feed $feed
     */
    public function remove(Feed $feed)
    {
        $entityManager = $this->getEntityManager();

        $entityManager->remove($feed);
        $entityManager->flush($feed);
    }
}
