<?php

namespace Feedtags\ApplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedItemRepository extends EntityRepository
{
}
