<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130505194047 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE feeditem ADD feed_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE feeditem ADD CONSTRAINT FK_F9B86D1951A5BC03 FOREIGN KEY (feed_id) REFERENCES Feed (id)");
        $this->addSql("CREATE INDEX IDX_F9B86D1951A5BC03 ON feeditem (feed_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE FeedItem DROP FOREIGN KEY FK_F9B86D1951A5BC03");
        $this->addSql("DROP INDEX IDX_F9B86D1951A5BC03 ON FeedItem");
        $this->addSql("ALTER TABLE FeedItem DROP feed_id");
    }
}
