parameters:
#    feedtags_application.example.class: Feedtags\ApplicationBundle\Example

services:
#    feedtags_application.example:
#        class: %feedtags_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
