parameters:
#    feedtags_frontend.example.class: Feedtags\FrontendBundle\Example

services:
#    feedtags_frontend.example:
#        class: %feedtags_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
